In [2]:
#Question 1
import numpy as np

A = np.array([[1, 2, 3], [2, 1, 3], [3, 2, 1]])
x = A.tolist()

print(A)
print(x)
print(A.shape[0])


[[1 2 3]
 [2 1 3]
 [3 2 1]]
[[1, 2, 3], [2, 1, 3], [3, 2, 1]]
3


In [3]:
# Question 2
# Manual Method
import numpy as np

A = np.array([[1, 2, 3], [2, 1, 3], [3, 2, 1]])

def diag_sum(arr1):
    result = 0
    for i in range(len(arr1)):
        result += arr1[i][i]

    print(result)

diag_sum(A)

# Trace Function
print(np.trace(A))

3
3


In [4]:
# Question 3
import numpy as np

a = np.array([[1, 2], [3, 5]])


def Get_Values_Greater_than_Value(arr1, val):
    Rlist = []
    for i in range(len(arr1)):
        for n in range(len(arr1[i])):
            if arr1[i][n] > val:
                Rlist.append(arr1[i][n])
    print(Rlist)


Get_Values_Greater_than_Value(a, 2)

[3, 5]


In [8]:
# Question 4
import numpy as np

A = np.array([[1, 2], [3, 5]])
B = np.array([[1, 2], [3, 5]])

def arr_sum(arr1, arr2):
    Rlist = []
    for i in range(len(arr1)):
        subList = []
        for n in range(len(arr1[i])):
            subList.append(arr1[i][n]+arr2[i][n])
        Rlist.append(subList)
    C = np.array(Rlist)
    return C

C = arr_sum(A, B)
print(C)

[[ 2  4]
 [ 6 10]]


In [10]:
# Question 5
import numpy as np
from statistics import mean

A = np.array([[1, 2], [3, 5]])

def mean_sub(arr1):
    li = arr1.tolist()
    result = 0
    Rlist = []
    for i in range(len(li)):
        Rlist.append(mean(li[i]))
    for n in range(len(Rlist)):
        if n == 0:
            result = Rlist[n]
        else:
            result -= Rlist[n]

    print(result)

mean_sub(A)

-2.5
